new task for CD pipeline

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -28,5 +28,8 @@ jobs:
           push: true
           tags: xborz75/my-first-app:latest
 
-      - name: Debug - Check Docker images pushed
-        run: docker images
+      - name: Debug - List Docker images before push
+        run: |
+          docker images
+          docker image inspect xborz75/my-first-app:latest || echo "Image not found"
+u
